before_script: 
  - cd code/travelapp-boot/
  - echo $TRAVIS_BUILD_DIR
  - echo "Sai "

cache:
  directories:
    - $HOME/.m2
    
script:
  - echo $TRAVIS_BUILD_DIR
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mkdir build
  - cp target/travelapp-0.0.1-SNAPSHOT.jar build/travelapp.jar  

deploy:
   provider: elasticbeanstalk
   skip_cleanup: true
   app: travelapp
   env: Travelapp-env-1
   zip_file: $TRAVIS_BUILD_DIR/build/travelapp.jar
   bucket_name: elasticbeanstalk-us-east-1-414657016646
   region: us-east-1
   access_key_id:
     secure: $ACCESSKEYID
   secret_access_key:
     secure: $SECRETACCESSKEY
   on:
     branch: master
